@startuml
entity Transaction {
    +transactionId: String
    +inputs: List<UTXO>
    +outputs: List<UTXO>
    +pools: List<PooledInput>
}

entity PooledInput {
    +address: ErgoAddress
    +filter: Option<Predicate>
    +value: Long
    +signature: Array<Byte>
}

entity UTXO {
    +utxoId: String
    +value: Long
    +blockHeight: Int
    +outputIndex: Int
}

entity Wallet {
    +walletId: String
    +address: ErgoAddress
    +utxos: List<UTXO>
}

entity ErgoNode {
    +nodeId: String
}

entity Block {
    +blockId: String
    +previousBlockId: String
    +blockHeight: Int
    +transactions: List<Transaction>
}
entity Address {
}
Transaction "1" -- "0..*" PooledInput : pools
Transaction "1" -- "0..*" UTXO : inputs
Transaction "1" -- "1..*" UTXO : outputs
Wallet "1" -- "*" Address : has access to
Wallet "1..*" -- "1" ErgoNode : interacts with
ErgoNode "1" -- "*" Block : creates
ErgoNode "1" -- "*" Transaction : processes
Block "1" -- "1..*" Transaction : contains
PooledInput "*" -- "1" Address : spends from
UTXO "0..*" -- "1" Block : created in
@enduml
